sudo: required
language: rust
env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib

script:
    - cargo build
    - cargo test
    - cargo doc

after_success: |
  bash scripts/travis-install-kcov.sh
  bash scripts/coverage.sh
